### PR TITLE
final changes to portfolio

### PR DESCRIPTION
**Pull request by zemiarsi**

### CODE REVIEW

**Comment by chase104** [comment]
Hi Betelehem,

I just reviewed your portfolio and I have to say that you've done some great work! Your fetches work perfectly and the css in your portfolio is quite good! Keep up the great work and you'll be a pro in no time.

Looking though and playing with your portfolio, I did find a minor css issue that has a quick fix.   
Under "skills" some of the longer texts are aligning left in the <li> divs. You can fix this by adding 'text-align: center' to the <p> tags in the <li> tags!

Great work!

Let me know if you have any questions!

**Comment by zemiarsi** [comment]
Good Morning,

Thanks for positive feedback, do I need to merge  after I fix the issues ?

Thanks,
Betelehem.

**Comment by chase104** [comment]
No need to merge unless you're going to be using the portfolio in future projects!

Thanks,

Chase

**Comment by zemiarsi** [comment]
Okay Thanks

**Pull request merged**
